#!/bin/sh
GANTRY_START=$@
SRC=$GANTRY_TEMPLATE
DST=$GANTRY_TARGET
ADDR=`echo $GANTRY_PORT | awk -F'//' '{print $2}' | awk -F: '{print $1" "$2}'`
PID=$$

conf(){
  NLINES=`wc -l $SRC | awk '{print $1}'`
  PARAMS=`env | grep "^GANTRY_"`
  NPARAMS=`echo "$PARAMS" | wc -l | awk '{print $1}'`
  (echo "$PARAMS"; cat $SRC) | \
  awk -v nlines=$NLINES -v nparams=$NPARAMS -v arg=$1 '
    BEGIN{printf "%s %s %s\n", nlines, nparams, arg}
    {print $0}
  ' | nc $ADDR | awk -v DST=$DST '
    NR==1{print}
    NR>=2{print > DST}
  '
}
killsilent(){
  kill $1 $2 2>/dev/null
}
killtree(){
  local P=$1
  PIDS=`ps -o ppid,pid | awk 'NR>1{print}' | grep "^$P\b" | awk '{print $2}'`
  for I in $PIDS; do killtree $I; done
  killsilent -TERM $P
}
DIGEST=`conf fetch`
while [ "$DIGEST" != '' ]; do
  NEW_DIGEST=`conf watch`
  if [ "$NEW_DIGEST" = '' ]; then
    echo gantry server down. retry...
    sleep 3
  elif [ "$DIGEST" != "$NEW_DIGEST" ]; then
    if $GANTRY_CHECK && $GANTRY_RELOAD; then
      DIGEST=$NEW_DIGEST
      echo "update $DST (digest=$DIGEST)"
    else
      echo "failed to reload (digest=$NEW_DIGEST) retry..."
      sleep 3
    fi
  fi
done &
WATCH_PID=$!
if [ "$DIGEST" != '' ]; then
  echo "new $DST (digest=$DIGEST)"
  if $GANTRY_CHECK; then exec $GANTRY_START; fi
  killtree $WATCH_PID
else
  echo "failed to start"
  exit 1
fi
